"""Tests for the approval cutoff economics."""

from __future__ import annotations

import numpy as np
import pandas as pd
import pytest

from src.policy import (
    break_even_pd,
    break_even_score,
    profit_at_cutoff,
    profit_curve,
    sensitivity,
)
from src.scorecard import probability_to_score, score_to_odds


class TestBreakEven:
    def test_formula(self):
        """margin / (margin + loss). At 800 against 6,000 that is 11.76%."""
        assert break_even_pd(800, 6000) == pytest.approx(800 / 6800)
        assert break_even_pd(800, 6000) == pytest.approx(0.117647, abs=1e-6)

    def test_depends_only_on_the_ratio(self):
        """Scaling both sides leaves the threshold alone, so loan size drops out."""
        assert break_even_pd(800, 6000) == pytest.approx(break_even_pd(80, 600))
        assert break_even_pd(800, 6000) == pytest.approx(break_even_pd(8000, 60000))

    def test_bigger_losses_demand_a_safer_borrower(self):
        assert break_even_pd(800, 12000) < break_even_pd(800, 6000)

    def test_equal_margin_and_loss_breaks_even_at_a_coin_flip(self):
        assert break_even_pd(1000, 1000) == pytest.approx(0.5)

    def test_score_conversion_is_the_scorecard_formula(self):
        assert break_even_score(800, 6000) == pytest.approx(
            probability_to_score(break_even_pd(800, 6000))
        )

    def test_higher_loss_ratio_raises_the_cutoff(self):
        assert break_even_score(800, 25000) > break_even_score(800, 2000)


@pytest.fixture
def book():
    """20,000 applicants whose risk follows the score scale exactly.

    p_bad is generated by inverting the score, so this book is perfectly
    calibrated to the PDO relation by construction. That is what makes the
    break-even comparison below meaningful: any gap the sweep finds on real data
    is a calibration effect, and here there is nothing to be calibrated against
    except the scale itself.
    """
    rng = np.random.default_rng(3)
    n = 20_000
    scores = pd.Series(rng.normal(580, 35, n))
    p_bad = 1.0 / (1.0 + score_to_odds(scores))
    y = pd.Series((rng.random(n) < p_bad).astype(int))
    return scores, y


class TestProfitAtCutoff:
    def test_approving_nobody_earns_nothing(self, book):
        scores, y = book
        out = profit_at_cutoff(scores, y, scores.max() + 1)
        assert out["n_approved"] == 0
        assert out["profit"] == 0.0
        assert out["approved_bad_rate"] == 0.0

    def test_approving_everyone_matches_the_portfolio(self, book):
        scores, y = book
        out = profit_at_cutoff(scores, y, scores.min() - 1)
        assert out["approval_rate"] == 1.0
        assert out["approved_bad_rate"] == pytest.approx(y.mean())

    def test_profit_arithmetic(self):
        scores = pd.Series([500.0, 600.0, 700.0])
        y = pd.Series([1, 0, 0])
        out = profit_at_cutoff(scores, y, 550, margin=800, loss=6000)
        # two approved, both good
        assert out["n_approved"] == 2
        assert out["profit"] == pytest.approx(2 * 800)

        out_all = profit_at_cutoff(scores, y, 400, margin=800, loss=6000)
        # three approved, one bad
        assert out_all["profit"] == pytest.approx(2 * 800 - 6000)

    def test_raising_the_cutoff_lowers_the_approved_bad_rate(self, book):
        scores, y = book
        low = profit_at_cutoff(scores, y, 550)
        high = profit_at_cutoff(scores, y, 600)
        assert high["approved_bad_rate"] < low["approved_bad_rate"]
        assert high["approval_rate"] < low["approval_rate"]


class TestProfitCurve:
    def test_spans_the_whole_score_range(self, book):
        scores, y = book
        curve = profit_curve(scores, y)
        assert curve["cutoff"].min() <= scores.min()
        assert curve["cutoff"].max() >= scores.max()

    def test_optimum_is_interior_not_at_an_end(self, book):
        """A real trade-off has its best point in the middle.

        Cutting at the bottom books every default; cutting at the top books
        almost nothing. If the optimum sat at either end the economics would be
        degenerate and the whole exercise pointless.
        """
        scores, y = book
        curve = profit_curve(scores, y)
        best = curve["profit"].idxmax()
        assert 0 < best < len(curve) - 1

    def test_optimum_lands_near_the_break_even_score(self, book):
        """The sweep and the closed form should agree to within a few points.

        They can differ, and the difference is a calibration statement rather
        than a bug, but on data generated from the same odds relation the scores
        assume, they should be close.
        """
        scores, y = book
        curve = profit_curve(scores, y)
        empirical = curve.loc[curve["profit"].idxmax(), "cutoff"]
        assert abs(empirical - break_even_score()) < 8


class TestSensitivity:
    def test_cutoff_rises_with_the_loss_ratio(self, book):
        scores, y = book
        table = sensitivity(scores, y, loss_ratios=(2.5, 7.5, 25.0))
        assert table["theoretical_cutoff"].is_monotonic_increasing
        assert table["empirical_cutoff"].is_monotonic_increasing

    def test_approval_rate_falls_with_the_loss_ratio(self, book):
        scores, y = book
        table = sensitivity(scores, y, loss_ratios=(2.5, 7.5, 25.0))
        assert table["approval_rate"].is_monotonic_decreasing

    def test_profit_falls_with_the_loss_ratio(self, book):
        """Worse recovery cannot be modelled away; it just costs money."""
        scores, y = book
        table = sensitivity(scores, y, loss_ratios=(2.5, 7.5, 25.0))
        assert table["profit_per_application"].is_monotonic_decreasing
